name: Test and Deploy App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-ui-tests:
    name: Run UI Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install packages
      run: npm install

    - name: Download browsers
      run: npx playwright install

    - name: Start FE
      run: npm run start
    
    - name: Run Tests
      run: npx playwright test tests/ui.test.js
